### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by Salokin42** [jrzaurin/RecoTour#1]
Hello

small typo kaggel at "kaggel competitions download -c coupon-purchase-prediction"
should be "kaggle competitions download -c coupon-purchase-prediction"

Best regards and thank you four the great notebooks

PS: I also had the error 403 - Forbidden when trying to download the data. It is neccesary to accept the rules of the competition first on the kaggle website.

**Comment by jrzaurin** [comment]
Hi @Salokin42 

OK, I will make sure I add these comments. I will close it once done.

Cheers!
