### ISSUE TITLE
[Feature Request] Propose a new subsection/chapter

### ISSUE THREAD

**Issue by rnjv** [jrzaurin/RecoTour#2]
I hope you can provide a new subsection/chapter on LightGCN under Neural Collaborative Filtering.

Ref: https://arxiv.org/pdf/2002.02126.pdf

**Comment by jrzaurin** [comment]
Hey @rnjv 

sure!, if you want to contribute let me know, if not I will bring it to the repo as soon as I have a sec. 

I am quite close to finish implementing the Mult-VAE (Pytorch and MxNet) and I wanted to implement the Sequential Mult-VAE (also Pytorch and MxNet) afterwards. 

I will read the paper and if is easy I might bring that to the repo first

Many thanks for  the suggestion!

Cheers
J.
