### ISSUE TITLE
what version of pandas you use?

### ISSUE THREAD

**Issue by Sandy4321** [jrzaurin/RecoTour#4]
what version of pandas you use

since
for
https://github.com/jrzaurin/RecoTour/blob/master/Ponpare/Chapter02_Split_DataSet.ipynb

df_users['reg_date'] =  pd.to_datetime(df_users.reg_date, infer_datetime_format=True)
gives error
builtins.AttributeError: 'DataFrame' object has no attribute 'reg_date'

but 
it is ok
pd.to_datetime(df_users.REG_DATE, infer_datetime_format=True)
0       2012-03-28 14:14:18
1       2011-05-18 00:41:48
2       2011-06-13 16:36:58
3       2012-02-08 12:56:15

for
pd.__version__
'1.1.5'

**Comment by jrzaurin** [comment]
Hey @Sandy4321 

Sorry for the delay in replying, I am really busy these days. 

Well, it was ages ago, so I can't remember, but that looks more like so column naming problem than a pandas version (?)

Anyway, hope you solved it and if not let me know and I promise I will check quicker this time

**Comment by Sandy4321** [comment]
thanks for answer
I did not fixed issue
seems to be there maybe many issues with python packages version
yes it would be great to make it run on recent packages like pandas

**Comment by jrzaurin** [comment]
what the error is saying is that the `reg_date` column does not exists while `REG_DATE` does. In other words, maybe I lowered case all columns and the command is not there, maybe you forgot, but it you run

```python
df_users.columns = [c.lower() for c in df_user.columns] 
```

and then you run your first command should work
