### ISSUE TITLE
missing prefecture.txt

### ISSUE THREAD

**Issue by Smit24-git** [jrzaurin/RecoTour#5]
I'm not able to locate prefecture.txt file in the repository. I've downloaded the coupon purchase prediction dataset and unzip all the files in `recotour\datasets\Ponpare\data` directory.  this dataset is missing **prefecture.txt** file too.

the library is being set up using conda venv on windows 10.

I was having issues running the download data script file so, I manually downloaded the files and copied them into the above-mentioned directory.

**Comment by jrzaurin** [comment]
@Smit24-git sorry for the late reply!

I will add it to the library later
